spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Demo
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: ${DB_HIBERNATE_DDL_AUTO:update}
  mail:
    default-encoding: UTF-8
    host: smtp.sendgrid.net
    username: ${SENDGRID_APIKEY}
    password: ${SENDGRID_USERNAME}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
